name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        Database: ${{ secrets.Database }}
        ServiceBus:  ${{ secrets.ServiceBus }}
    - name: Restore dependencies
      run: dotnet restore
    - name: Add Secret ServiceBus
      run: dotnet user-secrets set "ServiceBus" "${{secrets.ServiceBus}}"
    - name: Add Secret Database
      run: dotnet user-secrets set "Database" "${{secrets.Database}}"
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
